alter table SHOP_PRODUCT_CONTENT add constraint FK_SHOP_PRODUCT_CONTENT_ON_FILEPRODUCT foreign key (FILEPRODUCT_ID) references SYS_FILE(ID);
alter table SHOP_PRODUCT_CONTENT add constraint FK_SHOP_PRODUCT_CONTENT_ON_PRODUCT foreign key (PRODUCT_ID) references SHOP_PRODUCT(ID);
create index IDX_SHOP_PRODUCT_CONTENT_ON_FILEPRODUCT on SHOP_PRODUCT_CONTENT (FILEPRODUCT_ID);
create index IDX_SHOP_PRODUCT_CONTENT_ON_PRODUCT on SHOP_PRODUCT_CONTENT (PRODUCT_ID);
